version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: job-board-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_board
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: job-board-app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: job_board
    volumes:
      - ./src:/var/www/html/
volumes:
  db_data:
