apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest # You can choose a specific version
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root" # IMPORTANT: Use the same strong password as in db.php
        - name: MYSQL_DATABASE
          value: "job_board"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-init-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS job_board;

    USE job_board;

    CREATE TABLE IF NOT EXISTS jobs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        company VARCHAR(255) NOT NULL,
        location VARCHAR(255),
        description TEXT NOT NULL,
        salary VARCHAR(100),
        email VARCHAR(255) NOT NULL,
        posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
