apiVersion: v1
kind: Service
metadata:
  name: job-board-app-service
spec:
  selector:
    app: job-board-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # We'll use Ingress to expose it externally