apiVersion: v1
kind: Service
metadata:
  name: bitcoin-app-service
  namespace: dev 
spec:
  type: LoadBalancer
  selector:
    app: bitcoin-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80