global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ubiowororuki@gmail.com'
  smtp_auth_username: 'ubiowororuki@gmail.com'
  smtp_auth_password: 'wmzhovqoachfcuid'  # Your app password, no spaces
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
- name: 'email-alert'
  email_configs:
  - to: 'ubiowororuki@gmail.com'
    send_resolved: true
